# Generated by Django 3.1.2 on 2020-10-08 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('SE', 'Software Engineering'), ('CSE', 'Computer System Engineering'), ('REE', 'Renewable Energy Engineering'), ('PDE', 'Product Design Engineering'), ('FBT', 'Food Business Technology'), ('BM', 'Business Mathematics')], default='SE', max_length=256, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='image/student')),
                ('nim', models.CharField(blank=True, max_length=32, null=True)),
                ('major', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.major')),
            ],
        ),
    ]
