# Generated by Django 3.1.2 on 2020-10-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(choices=[('Software Engineering', 'SE'), ('Computer System Engineering', 'CSE'), ('Renewable Energy Engineering', 'REE'), ('Product Design Engineering', 'PDE'), ('Food Business Technology', 'FBT'), ('Business Mathematics', 'BM')], default=0, max_length=256),
        ),
    ]
